// addToCartCheckout.js created with Cypress
//
// Start writing your Cypress tests below!
// If you're unfamiliar with how Cypress works,
// check out the link below and learn how to write your first test:
// https://on.cypress.io/writing-first-test
/* ==== Test Created with Cypress Studio ==== */
it('add items from the list and checkout', function() {
  /* ==== Generated with Cypress Studio ==== */
  cy.visit('https://www.saucedemo.com/');
  cy.get('[data-test="username"]').clear();
  cy.get('[data-test="username"]').type('standard_user');
  cy.get('[data-test="password"]').clear();
  cy.get('[data-test="password"]').type('secret_sauce');
  cy.get('[data-test="login-button"]').click();
  cy.get(':nth-child(1) > .inventory_item_description > .pricebar > .inventory_item_price').should('be.visible');
  cy.get(':nth-child(1) > .inventory_item_description > .pricebar > .inventory_item_price').should('have.text', '$29.99');
  cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('be.visible');
  cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('be.enabled');
  cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('have.text', 'Add to cart');
  cy.get('.shopping_cart_link').should('have.class', 'shopping_cart_link');
  cy.get('.shopping_cart_link').should('be.visible');
  cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click();
  cy.get('[data-test="remove-sauce-labs-backpack"]').should('have.text', 'Remove');
  cy.get('.shopping_cart_link').should('have.text', '1');
  cy.get(':nth-child(2) > .inventory_item_description > .pricebar > .inventory_item_price').should('be.visible');
  cy.get(':nth-child(2) > .inventory_item_description > .pricebar > .inventory_item_price').should('have.text', '$9.99');
  cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').should('have.text', 'Add to cart');
  cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click();
  cy.get('[data-test="remove-sauce-labs-bike-light"]').should('have.text', 'Remove');
  cy.get('.shopping_cart_badge').should('have.text', '2');
  cy.get('.shopping_cart_link').click();
  cy.get('.title').should('have.text', 'Your Cart');
  cy.get('[data-test="checkout"]').should('be.visible');
  cy.get('[data-test="checkout"]').should('have.text', 'Checkout');
  cy.get('[data-test="checkout"]').click();
  cy.get('[data-test="firstName"]').clear();
  cy.get('[data-test="firstName"]').type('standard');
  cy.get('[data-test="lastName"]').clear();
  cy.get('[data-test="lastName"]').type('user');
  cy.get('[data-test="postalCode"]').clear();
  cy.get('[data-test="postalCode"]').type('6010');
  cy.get('.title').should('be.visible');
  cy.get('.title').should('have.text', 'Checkout: Your Information');
  cy.get('[data-test="continue"]').should('be.visible');
  cy.get('[data-test="continue"]').should('be.enabled');
  cy.get('[data-test="continue"]').click();
  cy.get(':nth-child(3) > .cart_item_label > .item_pricebar > .inventory_item_price').should('have.text', '$29.99');
  cy.get(':nth-child(4) > .cart_item_label > .item_pricebar > .inventory_item_price').should('have.text', '$9.99');
  cy.get('.summary_subtotal_label').should('have.text', 'Item total: $39.98');
  cy.get('.summary_tax_label').should('have.text', 'Tax: $3.20');
  cy.get('.summary_total_label').should('have.text', 'Total: $43.18');
  cy.get('[data-test="finish"]').should('be.enabled');
  cy.get('[data-test="finish"]').should('be.visible');
  cy.get('[data-test="finish"]').should('have.text', 'Finish');
  cy.get('[data-test="finish"]').click();
  cy.get('#checkout_complete_container').should('have.text', 'THANK YOU FOR YOUR ORDERYour order has been dispatched, and will arrive just as fast as the pony can get there!Back Home');
  cy.get('[data-test="back-to-products"]').should('have.id', 'back-to-products');
  cy.get('[data-test="back-to-products"]').should('have.text', 'Back Home');
  cy.get('[data-test="back-to-products"]').click();
  /* ==== End Cypress Studio ==== */
});
  it('add items from the details and checkout', function() {
    /* ==== Generated with Cypress Studio ==== */
    cy.visit('https://www.saucedemo.com/');
    cy.get('[data-test="username"]').clear();
    cy.get('[data-test="username"]').type('standard_user');
    cy.get('[data-test="password"]').clear();
    cy.get('[data-test="password"]').type('secret_sauce');
    cy.get('[data-test="login-button"]').click();
    cy.get(':nth-child(3) > .inventory_item_description > .pricebar > .inventory_item_price').should('be.visible');
    cy.get(':nth-child(3) > .inventory_item_description > .pricebar > .inventory_item_price').should('have.text', '$15.99');
    cy.get('#item_1_title_link > .inventory_item_name').should('have.text', 'Sauce Labs Bolt T-Shirt');
    cy.get('#item_1_title_link > .inventory_item_name').should('be.visible');
    cy.get('#item_1_title_link > .inventory_item_name').click();
    cy.get('.inventory_details_price').should('be.visible');
    cy.get('.inventory_details_price').should('have.text', '$15.99');
    cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').should('have.text', 'Add to cart');
    cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').should('have.id', 'add-to-cart-sauce-labs-bolt-t-shirt');
    cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').click();
    cy.get('[data-test="back-to-products"]').should('have.id', 'back-to-products');
    cy.get('[data-test="back-to-products"]').should('have.text', 'Back to products');
    cy.get('[data-test="back-to-products"]').should('be.visible');
    cy.get('[data-test="back-to-products"]').should('be.enabled');
    cy.get('[data-test="back-to-products"]').click();
    cy.get('#item_5_title_link > .inventory_item_name').should('have.text', 'Sauce Labs Fleece Jacket');
    cy.get('#item_5_title_link > .inventory_item_name').should('be.visible');
    cy.get(':nth-child(4) > .inventory_item_description > .pricebar > .inventory_item_price').should('be.visible');
    cy.get(':nth-child(4) > .inventory_item_description > .pricebar > .inventory_item_price').should('have.text', '$49.99');
    cy.get('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').should('be.visible');
    cy.get('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').should('be.enabled');
    cy.get('[data-test="remove-sauce-labs-bolt-t-shirt"]').should('have.text', 'Remove');
    cy.get('[data-test="remove-sauce-labs-bolt-t-shirt"]').should('have.id', 'remove-sauce-labs-bolt-t-shirt');
    cy.get('#item_5_title_link > .inventory_item_name').click();
    cy.get('.inventory_details_price').should('have.text', '$49.99');
    cy.get('.inventory_details_price').should('be.visible');
    cy.get('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').should('have.id', 'add-to-cart-sauce-labs-fleece-jacket');
    cy.get('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').should('be.visible');
    cy.get('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').should('be.enabled');
    cy.get('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').click();
    cy.get('[data-test="remove-sauce-labs-fleece-jacket"]').should('have.id', 'remove-sauce-labs-fleece-jacket');
    cy.get('.shopping_cart_link').should('have.text', '2');
    cy.get('.shopping_cart_link').should('be.visible');
    cy.get('.shopping_cart_link').click();
    cy.get('.title').should('have.text', 'Your Cart');
    cy.get('[data-test="checkout"]').should('be.visible');
    cy.get('[data-test="checkout"]').should('be.enabled');
    cy.get('[data-test="checkout"]').should('have.text', 'Checkout');
    cy.get('[data-test="checkout"]').click();
    cy.get('[data-test="firstName"]').clear();
    cy.get('[data-test="firstName"]').type('standard');
    cy.get('[data-test="lastName"]').clear();
    cy.get('[data-test="lastName"]').type('user');
    cy.get('[data-test="postalCode"]').clear();
    cy.get('[data-test="postalCode"]').type('3004');
    cy.get('[data-test="continue"]').should('be.enabled');
    cy.get('[data-test="continue"]').should('be.visible');
    cy.get('[data-test="continue"]').should('have.value', 'Continue');
    cy.get('[data-test="continue"]').click();
    cy.get(':nth-child(3) > .cart_item_label > .item_pricebar > .inventory_item_price').should('have.text', '$15.99');
    cy.get(':nth-child(4) > .cart_item_label > .item_pricebar > .inventory_item_price').should('have.text', '$49.99');
    cy.get('.summary_subtotal_label').should('have.text', 'Item total: $65.98');
    cy.get('.summary_tax_label').should('have.text', 'Tax: $5.28');
    cy.get('.summary_total_label').should('have.text', 'Total: $71.26');
    cy.get('.summary_total_label').should('have.class', 'summary_total_label');
    cy.get('.summary_total_label').should('be.visible');
    cy.get('[data-test="finish"]').should('be.enabled');
    cy.get('[data-test="finish"]').should('be.visible');
    cy.get('[data-test="finish"]').should('have.text', 'Finish');
    cy.get('[data-test="finish"]').should('have.id', 'finish');
    cy.get('[data-test="finish"]').click();
    cy.get('#checkout_complete_container').should('have.text', 'THANK YOU FOR YOUR ORDERYour order has been dispatched, and will arrive just as fast as the pony can get there!Back Home');
    cy.get('#checkout_complete_container').should('have.id', 'checkout_complete_container');
    cy.get('[data-test="back-to-products"]').should('be.visible');
    cy.get('[data-test="back-to-products"]').should('be.enabled');
    cy.get('[data-test="back-to-products"]').click();
    /* ==== End Cypress Studio ==== */
  });
  it('remove items from list and details', function() {
    /* ==== Generated with Cypress Studio ==== */
    cy.visit('https://www.saucedemo.com/');
    cy.get('[data-test="username"]').clear();
    cy.get('[data-test="username"]').type('standard_user');
    cy.get('[data-test="password"]').clear();
    cy.get('[data-test="password"]').type('secret_sauce');
    cy.get('[data-test="login-button"]').click();
    cy.get('.shopping_cart_link').should('have.class', 'shopping_cart_link');
    cy.get('.shopping_cart_link').should('be.visible');
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('be.visible');
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('be.enabled');
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('have.text', 'Add to cart');
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click();
    cy.get('.shopping_cart_badge').should('have.text', '1');
    cy.get('.shopping_cart_link').should('have.class', 'shopping_cart_link');
    cy.get('.shopping_cart_badge').should('have.class', 'shopping_cart_badge');
    cy.get('.shopping_cart_badge').should('be.visible');
    cy.get('[data-test="remove-sauce-labs-backpack"]').should('be.enabled');
    cy.get('[data-test="remove-sauce-labs-backpack"]').should('be.visible');
    cy.get('[data-test="remove-sauce-labs-backpack"]').should('have.text', 'Remove');
    cy.get('[data-test="remove-sauce-labs-backpack"]').should('have.id', 'remove-sauce-labs-backpack');
    cy.get('[data-test="remove-sauce-labs-backpack"]').click();
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('have.text', 'Add to cart');
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('have.id', 'add-to-cart-sauce-labs-backpack');
    cy.get('.shopping_cart_link').should('have.class', 'shopping_cart_link');
    cy.get('#item_4_title_link > .inventory_item_name').click();
    cy.get('.shopping_cart_link').should('have.class', 'shopping_cart_link');
    cy.get('.shopping_cart_link').should('be.visible');
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('have.text', 'Add to cart');
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('have.id', 'add-to-cart-sauce-labs-backpack');
    cy.get('.inventory_details_desc_container').click();
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click();
    cy.get('[data-test="remove-sauce-labs-backpack"]').should('have.text', 'Remove');
    cy.get('[data-test="remove-sauce-labs-backpack"]').should('have.id', 'remove-sauce-labs-backpack');
    cy.get('.shopping_cart_badge').should('have.text', '1');
    cy.get('.shopping_cart_badge').should('have.class', 'shopping_cart_badge');
    cy.get('.shopping_cart_link').should('have.class', 'shopping_cart_link');
    cy.get('[data-test="remove-sauce-labs-backpack"]').click();
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('be.visible');
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('be.enabled');
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('have.text', 'Add to cart');
    cy.get('.shopping_cart_link').should('have.class', 'shopping_cart_link');
    cy.get('.shopping_cart_link').should('be.visible');
    /* ==== End Cypress Studio ==== */
  });
